apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8123
  type: {{ .Values.service.type }}
